#!/usr/bin/env python3
"""Regenerate the environment-variables guide page from Doxygen XML.

The SDK documents every configuration key it reads with a Doxygen
`@note Configuration key: \\`SOME__KEY\\` (default: ...)` annotation on the
accessor that reads it (see Configuration.h). This script parses the
Doxygen XML output (produced by `doxygen tools/Doxyfile`, which must run
first) for that pattern and writes a single Markdown table, so the guide
page can never drift from the annotations it is generated from.

To document a new environment variable, add the same `@note Configuration
key: \\`KEY\\` (default: ... | optional)` annotation to its accessor and
re-run the docs build; no other step is needed.
"""
import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
XML_DIR = os.path.join(REPO_ROOT, ".docs", "content", "cpp", "doxygen", "xml")
OUTPUT_PATH = os.path.join(REPO_ROOT, ".docs", "content", "guide", "4.environment-variables.md")
GITHUB_BLOB = "https://github.com/aneoconsulting/ArmoniK.Extensions.Cpp/blob/main"

SKIP_FILES = {"index.xml", "Doxyfile.xml"}
KEY_RE = re.compile(r"Configuration key:\s*`([A-Za-z0-9_]+)`\s*(?:\(([^)]*)\))?")


def flatten(el):
  """Join all text of an element, including inside nested tags such as <ref>."""
  return "".join(el.itertext()).strip()


def iter_memberdefs():
  for path in sorted(glob.glob(os.path.join(XML_DIR, "*.xml"))):
    if os.path.basename(path) in SKIP_FILES:
      continue
    try:
      root = ET.parse(path).getroot()
    except ET.ParseError:
      continue
    for memberdef in root.iter("memberdef"):
      yield memberdef


def extract_entries():
  entries = {}
  for memberdef in iter_memberdefs():
    name_el = memberdef.find("qualifiedname")
    if name_el is None:
      name_el = memberdef.find("name")
    symbol = flatten(name_el) if name_el is not None else "?"

    brief_el = memberdef.find("briefdescription/para")
    description = flatten(brief_el) if brief_el is not None else ""

    loc = memberdef.find("location")
    file_ref = loc.get("file") if loc is not None else None
    line = loc.get("line") if loc is not None else None

    key_match = None
    other_notes = []
    for note in memberdef.iter("simplesect"):
      if note.get("kind") != "note":
        continue
      para = note.find("para")
      if para is None:
        continue
      text = flatten(para)
      match = KEY_RE.search(text)
      if match and key_match is None:
        key_match = match
      else:
        other_notes.append(text)

    if key_match is None:
      continue

    var_name, extra = key_match.group(1), (key_match.group(2) or "").strip()
    full_description = " ".join([description] + other_notes) if other_notes else description
    entries.setdefault(var_name, {
        "var": var_name,
        "extra": extra,
        "description": full_description,
        "symbol": symbol,
        "file": file_ref,
        "line": line,
    })
  return entries


def format_default(extra):
  if not extra:
    return "*(required)*"
  default_match = re.search(r"default:\s*(.+)", extra, re.IGNORECASE)
  if default_match:
    return f"`{default_match.group(1).strip()}`"
  if "optional" in extra.lower():
    return "*(optional)*"
  return extra


def escape_cell(text):
  return text.replace("|", "\\|")


def render(entries):
  rows = sorted(entries.values(), key=lambda e: e["var"])
  lines = [
      "<!-- AUTO-GENERATED by tools/docs/generate_env_vars_table.py -- do not edit by hand. -->",
      "<!-- Regenerated from `@note Configuration key:` Doxygen annotations on every docs build. -->",
      "",
      "# Environment variables",
      "",
      "Every configuration key read by ArmoniK.Extensions.Cpp itself (via "
      "`Configuration::add_env_configuration()`, or the equivalent JSON configuration key). This "
      "table is generated from the `Configuration key:` notes attached to the accessors in the "
      "C++ source: to document a new environment variable, annotate its accessor the same way "
      "and it appears here automatically on the next docs build.",
      "",
      "The gRPC channel itself (keep-alive, retry/backoff, request timeout) is configured by the "
      "underlying [ArmoniK.Api](https://github.com/aneoconsulting/ArmoniK.Api) client library from "
      "the same `Configuration` object, using its own `GrpcClient__*` keys (`KeepAliveTime`, "
      "`MaxAttempts`, `BackoffMultiplier`, `RequestTimeout`, etc.). Those are documented in "
      "[ArmoniK.Api's environment variables reference]"
      "(https://armonikapi.readthedocs.io/en/latest/content/usage/envars/ArmoniK.Api.EnvVars.html), "
      "not repeated here.",
      "",
      "| Variable | Default | Description | Defined in |",
      "|---|---|---|---|",
  ]
  for e in rows:
    default = format_default(e["extra"])
    if e["file"]:
      link = f"[`{e['symbol']}`]({GITHUB_BLOB}/{e['file']}#L{e['line']})"
    else:
      link = f"`{e['symbol']}`"
    lines.append(f"| `{e['var']}` | {escape_cell(default)} | {escape_cell(e['description'])} | {escape_cell(link)} |")
  lines.append("")
  return "\n".join(lines)


def main():
  if not os.path.isdir(XML_DIR):
    sys.exit(f"Doxygen XML not found at {XML_DIR}; run `doxygen tools/Doxyfile` first")

  entries = extract_entries()
  if not entries:
    sys.exit("No `Configuration key:` annotations found in the Doxygen XML")

  os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
  with open(OUTPUT_PATH, "w") as f:
    f.write(render(entries))
  print(f"Wrote {len(entries)} environment variable(s) to {OUTPUT_PATH}")


if __name__ == "__main__":
  main()
