function(setup_options project_name_param)

    if(${ARGC} GREATER 1)
        set(extra_param ${ARGV1})
    endif()

    if(MSVC)
        target_compile_options(${project_name_param} PRIVATE /W4)
    else()
        file(READ /etc/issue ${PROJECT_NAME}_ETCISSUE_CONTENT)
        string(FIND "${${project_name_param}_ETCISSUE_CONTENT}" "Alpine" IS_ALPINE)
        if(CMAKE_BUILD_TYPE MATCHES DEBUG AND IS_ALPINE EQUAL -1)
            target_compile_options(${project_name_param} PRIVATE -Wall -Wextra -Wpedantic -fsanitize=undefined,address ${extra_param})
        else ()
            target_compile_options(${project_name_param} PRIVATE -Wall -Wextra -Wpedantic ${extra_param})
        endif()
    endif()

    if(CMAKE_BUILD_TYPE MATCHES DEBUG AND IS_ALPINE EQUAL -1)
        target_link_options(${project_name_param} PRIVATE -fsanitize=undefined,address ${extra_param})
    endif()
endfunction()

function(split_version version_param)
    string(REGEX MATCHALL "[0-9]+" VERSION_LIST ${version_param})
    list(GET VERSION_LIST 0 VERSION_MAJOR)
    list(GET VERSION_LIST 1 VERSION_MINOR)
    list(GET VERSION_LIST 2 VERSION_PATCH)
endfunction()

function(setup_lib_version project_name_param)
    set_property(TARGET ${project_name_param} PROPERTY VERSION ${VERSION})
    set_property(TARGET ${project_name_param} PROPERTY SOVERSION ${VERSION_MAJOR})
    set_property(TARGET ${project_name_param} PROPERTY INTERFACE_${project_name_param}_MAJOR_VERSION ${VERSION_MAJOR})
    set_property(TARGET ${project_name_param} APPEND PROPERTY COMPATIBLE_INTERFACE_STRING ${project_name_param}_MAJOR_VERSION)
endfunction()
